/* Generated By:JJTree: Do not edit this line. ASTlhs_identifier.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTlhs_identifier extends SimpleNode {
  public ASTlhs_identifier(int id) {
    super(id);
  }

  public ASTlhs_identifier(HOPE3 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HOPE3Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=2d343079caba4b3bb02447945ab44662 (do not edit this line) */
