/* Generated By:JJTree: Do not edit this line. ASTrhs_identifier.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTrhs_identifier extends SimpleNode {
  public ASTrhs_identifier(int id) {
    super(id);
  }

  public ASTrhs_identifier(HOPE3 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HOPE3Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=0882feca8b2caf3b3e1578d95c30d724 (do not edit this line) */
