/* Generated By:JJTree: Do not edit this line. ASTstatement_block.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTstatement_block extends SimpleNode {
  public ASTstatement_block(int id) {
    super(id);
  }

  public ASTstatement_block(HOPE3 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HOPE3Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=3666b616f23aeacbbf33c1962cf59e49 (do not edit this line) */
