/* Generated By:JavaCC: Do not edit this line. HOPE3TreeConstants.java Version 5.0 */
public interface HOPE3TreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTSTATEMENT_BLOCK = 1;
  public int JJTSTATEMENT = 2;
  public int JJTVOID = 3;
  public int JJTEXPRESSION = 4;
  public int JJTINTEGER = 5;
  public int JJTSTRING = 6;
  public int JJTBOOL = 7;
  public int JJTASSIGNMENT = 8;
  public int JJTDECLARATION = 9;
  public int JJTPRINT = 10;
  public int JJTLHS_IDENTIFIER = 11;
  public int JJTRHS_IDENTIFIER = 12;
  public int JJTTYPE = 13;
  public int JJTBINARY_ARITH_OP = 14;
  public int JJTBINARY_LOGIC_OP = 15;


  public String[] jjtNodeName = {
    "program",
    "statement_block",
    "statement",
    "void",
    "expression",
    "integer",
    "string",
    "bool",
    "assignment",
    "declaration",
    "print",
    "lhs_identifier",
    "rhs_identifier",
    "type",
    "binary_arith_op",
    "binary_logic_op",
  };
}
/* JavaCC - OriginalChecksum=06134dbad5ba35e64c0f7d8cff12df6b (do not edit this line) */
