/* Generated By:JJTree: Do not edit this line. ASTarith_op.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTarith_op extends SimpleNode {
  public ASTarith_op(int id) {
    super(id);
  }

  public ASTarith_op(HOPE7 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HOPE7Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=0d6fb388ee3b7cf89fd000cb0523d67b (do not edit this line) */
