/* Generated By:JJTree: Do not edit this line. ASTfunction_declarations.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTfunction_declarations extends SimpleNode {
  public ASTfunction_declarations(int id) {
    super(id);
  }

  public ASTfunction_declarations(HOPE7 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HOPE7Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=3275d14c1ca46638fec3c48ca0fb7a6a (do not edit this line) */
