/* Generated By:JJTree: Do not edit this line. ASTlogic_op.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTlogic_op extends SimpleNode {
  public ASTlogic_op(int id) {
    super(id);
  }

  public ASTlogic_op(HOPE7 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HOPE7Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=04cd059babb2ac3ff5d3516407c804ba (do not edit this line) */
