/* Generated By:JJTree: Do not edit this line. ASTreturn_type.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTreturn_type extends SimpleNode {
  public ASTreturn_type(int id) {
    super(id);
  }

  public ASTreturn_type(HOPE7 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HOPE7Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c59fe5de9caefdba92f69de1c3f955f4 (do not edit this line) */
