/* Generated By:JavaCC: Do not edit this line. HOPE7TreeConstants.java Version 5.0 */
public interface HOPE7TreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTMAIN = 1;
  public int JJTFUNCTION_DECLARATIONS = 2;
  public int JJTFUNCTION = 3;
  public int JJTPARAMETER_LIST = 4;
  public int JJTPARAMETER = 5;
  public int JJTSTATEMENT_BLOCK = 6;
  public int JJTSTATEMENT = 7;
  public int JJTASSIGNMENT = 8;
  public int JJTDECLARATION = 9;
  public int JJTARRAY_DECLARATION = 10;
  public int JJTARRAY_SIZE = 11;
  public int JJTPRINT = 12;
  public int JJTIF_STATEMENT = 13;
  public int JJTWHILE_LOOP = 14;
  public int JJTFUNCTION_CALL = 15;
  public int JJTARGUMENT_LIST = 16;
  public int JJTARGUMENT = 17;
  public int JJTEXPRESSION = 18;
  public int JJTCONDITION = 19;
  public int JJTFRAGMENT = 20;
  public int JJTINTEGER = 21;
  public int JJTSTRING = 22;
  public int JJTBOOL = 23;
  public int JJTARRAY = 24;
  public int JJTARRAY_INDEX = 25;
  public int JJTINDEX = 26;
  public int JJTLHS_IDENTIFIER = 27;
  public int JJTRHS_IDENTIFIER = 28;
  public int JJTTYPE = 29;
  public int JJTBINARY_ARITH_OP = 30;
  public int JJTARITH_OP = 31;
  public int JJTBINARY_LOGIC_OP = 32;
  public int JJTLOGIC_OP = 33;
  public int JJTCOMP_OP = 34;


  public String[] jjtNodeName = {
    "program",
    "main",
    "function_declarations",
    "function",
    "parameter_list",
    "parameter",
    "statement_block",
    "statement",
    "assignment",
    "declaration",
    "array_declaration",
    "array_size",
    "print",
    "if_statement",
    "while_loop",
    "function_call",
    "argument_list",
    "argument",
    "expression",
    "condition",
    "fragment",
    "integer",
    "string",
    "bool",
    "array",
    "array_index",
    "index",
    "lhs_identifier",
    "rhs_identifier",
    "type",
    "binary_arith_op",
    "arith_op",
    "binary_logic_op",
    "logic_op",
    "comp_op",
  };
}
/* JavaCC - OriginalChecksum=23ab2392793e30d60b598b5e80684b02 (do not edit this line) */
