/* Generated By:JavaCC: Do not edit this line. HOPE7TreeConstants.java Version 5.0 */
public interface HOPE7TreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTMAIN = 1;
  public int JJTFUNCTION_DECLARATIONS = 2;
  public int JJTFUNCTION = 3;
  public int JJTRETURN_TYPE = 4;
  public int JJTPARAMETER_LIST = 5;
  public int JJTPARAMETER = 6;
  public int JJTSTATEMENT_BLOCK = 7;
  public int JJTSTATEMENT = 8;
  public int JJTASSIGNMENT = 9;
  public int JJTDECLARATION = 10;
  public int JJTARRAY_DECLARATION = 11;
  public int JJTARRAY_SIZE = 12;
  public int JJTPRINT = 13;
  public int JJTIF_STATEMENT = 14;
  public int JJTWHILE_LOOP = 15;
  public int JJTFUNCTION_CALL = 16;
  public int JJTARGUMENT_LIST = 17;
  public int JJTARGUMENT = 18;
  public int JJTEXPRESSION = 19;
  public int JJTCONDITION = 20;
  public int JJTFRAGMENT = 21;
  public int JJTINTEGER = 22;
  public int JJTFLOATING_POINT = 23;
  public int JJTSTRING = 24;
  public int JJTBOOL = 25;
  public int JJTARRAY = 26;
  public int JJTARRAY_INDEX = 27;
  public int JJTLHS_IDENTIFIER = 28;
  public int JJTRHS_IDENTIFIER = 29;
  public int JJTTYPE = 30;
  public int JJTARITH_OP = 31;
  public int JJTLOGIC_OP = 32;
  public int JJTCOMP_OP = 33;
  public int JJTSKIP = 34;


  public String[] jjtNodeName = {
    "program",
    "main",
    "function_declarations",
    "function",
    "return_type",
    "parameter_list",
    "parameter",
    "statement_block",
    "statement",
    "assignment",
    "declaration",
    "array_declaration",
    "array_size",
    "print",
    "if_statement",
    "while_loop",
    "function_call",
    "argument_list",
    "argument",
    "expression",
    "condition",
    "fragment",
    "integer",
    "floating_point",
    "string",
    "bool",
    "array",
    "array_index",
    "lhs_identifier",
    "rhs_identifier",
    "type",
    "arith_op",
    "logic_op",
    "comp_op",
    "skip",
  };
}
/* JavaCC - OriginalChecksum=8d17a56826a26ff1f40417f8c6b2a761 (do not edit this line) */
