/* Generated By:JJTree&JavaCC: Do not edit this line. HOPE7Constants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface HOPE7Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PRINT = 13;
  /** RegularExpression Id. */
  int INT = 14;
  /** RegularExpression Id. */
  int STRING = 15;
  /** RegularExpression Id. */
  int BOOL = 16;
  /** RegularExpression Id. */
  int FLOAT = 17;
  /** RegularExpression Id. */
  int VOID = 18;
  /** RegularExpression Id. */
  int TRUE = 19;
  /** RegularExpression Id. */
  int FALSE = 20;
  /** RegularExpression Id. */
  int IF = 21;
  /** RegularExpression Id. */
  int ELSE = 22;
  /** RegularExpression Id. */
  int WHILE = 23;
  /** RegularExpression Id. */
  int DEF = 24;
  /** RegularExpression Id. */
  int MAIN = 25;
  /** RegularExpression Id. */
  int RETURN = 26;
  /** RegularExpression Id. */
  int LBR = 27;
  /** RegularExpression Id. */
  int RBR = 28;
  /** RegularExpression Id. */
  int SEMIC = 29;
  /** RegularExpression Id. */
  int PLUS_SIGN = 30;
  /** RegularExpression Id. */
  int MINUS_SIGN = 31;
  /** RegularExpression Id. */
  int MUL_SIGN = 32;
  /** RegularExpression Id. */
  int DIV_SIGN = 33;
  /** RegularExpression Id. */
  int EQUALS = 34;
  /** RegularExpression Id. */
  int OR = 35;
  /** RegularExpression Id. */
  int AND = 36;
  /** RegularExpression Id. */
  int QUOTE = 37;
  /** RegularExpression Id. */
  int LCB = 38;
  /** RegularExpression Id. */
  int RCB = 39;
  /** RegularExpression Id. */
  int EQ = 40;
  /** RegularExpression Id. */
  int NEQ = 41;
  /** RegularExpression Id. */
  int GT = 42;
  /** RegularExpression Id. */
  int LT = 43;
  /** RegularExpression Id. */
  int GE = 44;
  /** RegularExpression Id. */
  int LE = 45;
  /** RegularExpression Id. */
  int COMMA = 46;
  /** RegularExpression Id. */
  int LSB = 47;
  /** RegularExpression Id. */
  int RSB = 48;
  /** RegularExpression Id. */
  int MOD = 49;
  /** RegularExpression Id. */
  int DOT = 50;
  /** RegularExpression Id. */
  int NUM = 51;
  /** RegularExpression Id. */
  int FP = 52;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 53;
  /** RegularExpression Id. */
  int ID = 54;
  /** RegularExpression Id. */
  int STRING_LITERAL = 55;
  /** RegularExpression Id. */
  int LETTER = 56;
  /** RegularExpression Id. */
  int OTHER = 57;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_COMMENT = 1;
  /** Lexical state. */
  int IN_SINGLE_LINE_COMMENT = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"/*\"",
    "\"//\"",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 10>",
    "<token of kind 11>",
    "<token of kind 12>",
    "\"print\"",
    "\"int\"",
    "\"string\"",
    "\"boolean\"",
    "\"float\"",
    "\"void\"",
    "\"true\"",
    "\"false\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"def\"",
    "\"main\"",
    "\"return\"",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"=\"",
    "\"|\"",
    "\"&\"",
    "\"\\\"\"",
    "\"{\"",
    "\"}\"",
    "\"==\"",
    "\"!=\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\",\"",
    "\"[\"",
    "\"]\"",
    "\"%\"",
    "\".\"",
    "<NUM>",
    "<FP>",
    "<INTEGER_LITERAL>",
    "<ID>",
    "<STRING_LITERAL>",
    "<LETTER>",
    "<OTHER>",
  };

}
