/* Generated By:JavaCC: Do not edit this line. HOPE2Visitor.java Version 5.0 */
public interface HOPE2Visitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTprogram node, Object data);
  public Object visit(ASTstatement_block node, Object data);
  public Object visit(ASTstatement node, Object data);
  public Object visit(ASTexpression node, Object data);
  public Object visit(ASTinteger node, Object data);
  public Object visit(ASTassignment node, Object data);
  public Object visit(ASTdeclaration node, Object data);
  public Object visit(ASTprint node, Object data);
  public Object visit(ASTidentifier node, Object data);
  public Object visit(ASTtype node, Object data);
  public Object visit(ASTbinary_arith_op node, Object data);
}
/* JavaCC - OriginalChecksum=27b91f6f0a1d9047e5a73a3793afdbc0 (do not edit this line) */
