/* Generated By:JavaCC: Do not edit this line. HOPE2TreeConstants.java Version 5.0 */
public interface HOPE2TreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTSTATEMENT_BLOCK = 1;
  public int JJTSTATEMENT = 2;
  public int JJTVOID = 3;
  public int JJTEXPRESSION = 4;
  public int JJTINTEGER = 5;
  public int JJTASSIGNMENT = 6;
  public int JJTDECLARATION = 7;
  public int JJTPRINT = 8;
  public int JJTIDENTIFIER = 9;
  public int JJTTYPE = 10;
  public int JJTBINARY_ARITH_OP = 11;


  public String[] jjtNodeName = {
    "program",
    "statement_block",
    "statement",
    "void",
    "expression",
    "integer",
    "assignment",
    "declaration",
    "print",
    "identifier",
    "type",
    "binary_arith_op",
  };
}
/* JavaCC - OriginalChecksum=1d921c12269a8bfa31e7fbc4c2f33b05 (do not edit this line) */
