/* Generated By:JavaCC: Do not edit this line. HOPE2TreeConstants.java Version 5.0 */
public interface HOPE2TreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTSTATEMENT_BLOCK = 1;
  public int JJTSTATEMENT = 2;
  public int JJTVOID = 3;
  public int JJTEXPRESSION = 4;
  public int JJTINTEGER = 5;
  public int JJTASSIGNMENT = 6;
  public int JJTDECLARATION = 7;
  public int JJTPRINT = 8;
  public int JJTLHS_IDENTIFIER = 9;
  public int JJTRHS_IDENTIFIER = 10;
  public int JJTTYPE = 11;
  public int JJTBINARY_ARITH_OP = 12;


  public String[] jjtNodeName = {
    "program",
    "statement_block",
    "statement",
    "void",
    "expression",
    "integer",
    "assignment",
    "declaration",
    "print",
    "lhs_identifier",
    "rhs_identifier",
    "type",
    "binary_arith_op",
  };
}
/* JavaCC - OriginalChecksum=e1a099e133bdf7aa3a6dcd3f6c6502c8 (do not edit this line) */
