/* Generated By:JJTree: Do not edit this line. ASTfunction_declarations.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTfunction_declarations extends SimpleNode {
  public ASTfunction_declarations(int id) {
    super(id);
  }

  public ASTfunction_declarations(HOPEFUL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HOPEFULVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=1ba687ed93e13e8cbabdb83443e14d75 (do not edit this line) */
