/* Generated By:JJTree: Do not edit this line. ASTparameter.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTparameter extends SimpleNode {
  public ASTparameter(int id) {
    super(id);
  }

  public ASTparameter(HOPEFUL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HOPEFULVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c465c11bad2cc08970ce804278706fce (do not edit this line) */
