/* Generated By:JavaCC: Do not edit this line. HOPEFULTreeConstants.java Version 5.0 */
public interface HOPEFULTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTMAIN = 1;
  public int JJTFUNCTION_DECLARATIONS = 2;
  public int JJTFUNCTION = 3;
  public int JJTRETURN_TYPE = 4;
  public int JJTPARAMETER_LIST = 5;
  public int JJTPARAMETER = 6;
  public int JJTSTATEMENT_BLOCK = 7;
  public int JJTSTATEMENT = 8;
  public int JJTASSIGNMENT = 9;
  public int JJTDECLARATION = 10;
  public int JJTPRINT = 11;
  public int JJTIF_STATEMENT = 12;
  public int JJTWHILE_LOOP = 13;
  public int JJTFUNCTION_CALL = 14;
  public int JJTARGUMENT_LIST = 15;
  public int JJTARGUMENT = 16;
  public int JJTEXPRESSION = 17;
  public int JJTCONDITION = 18;
  public int JJTFRAGMENT = 19;
  public int JJTINTEGER = 20;
  public int JJTSTRING = 21;
  public int JJTBOOL = 22;
  public int JJTLHS_IDENTIFIER = 23;
  public int JJTRHS_IDENTIFIER = 24;
  public int JJTTYPE = 25;
  public int JJTARITH_OP = 26;
  public int JJTLOGIC_OP = 27;
  public int JJTCOMP_OP = 28;
  public int JJTSKIP = 29;


  public String[] jjtNodeName = {
    "program",
    "main",
    "function_declarations",
    "function",
    "return_type",
    "parameter_list",
    "parameter",
    "statement_block",
    "statement",
    "assignment",
    "declaration",
    "print",
    "if_statement",
    "while_loop",
    "function_call",
    "argument_list",
    "argument",
    "expression",
    "condition",
    "fragment",
    "integer",
    "string",
    "bool",
    "lhs_identifier",
    "rhs_identifier",
    "type",
    "arith_op",
    "logic_op",
    "comp_op",
    "skip",
  };
}
/* JavaCC - OriginalChecksum=66cf4564a02077c494469bc341c2e2f9 (do not edit this line) */
