/* Generated By:JJTree: Do not edit this line. ASTargument_list.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTargument_list extends SimpleNode {
  public ASTargument_list(int id) {
    super(id);
  }

  public ASTargument_list(HOPE6 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HOPE6Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ccb93eeb3bd472a5ee51419a70a627a0 (do not edit this line) */
