/* Generated By:JJTree: Do not edit this line. ASTarray_declaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTarray_declaration extends SimpleNode {
  public ASTarray_declaration(int id) {
    super(id);
  }

  public ASTarray_declaration(HOPE6 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HOPE6Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=115477abc0686f505b2c9b37b0ee3359 (do not edit this line) */
