/* Generated By:JJTree: Do not edit this line. ASTarray.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTarray extends SimpleNode {
  public ASTarray(int id) {
    super(id);
  }

  public ASTarray(HOPE6 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HOPE6Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=0cc6913e898c0ed8db65d009fe7cd13b (do not edit this line) */
