/* Generated By:JJTree: Do not edit this line. ASTbinary_logic_op.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTbinary_logic_op extends SimpleNode {
  public ASTbinary_logic_op(int id) {
    super(id);
  }

  public ASTbinary_logic_op(HOPE6 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HOPE6Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e2f16a01a2b2d31914c7dd874263634e (do not edit this line) */
