/* Generated By:JJTree: Do not edit this line. ASTfunction_call.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTfunction_call extends SimpleNode {
  public ASTfunction_call(int id) {
    super(id);
  }

  public ASTfunction_call(HOPE6 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HOPE6Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e213c45756a6f6202415e0e0defeaccf (do not edit this line) */
