/* Generated By:JJTree: Do not edit this line. ASTrhs_identifier.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTrhs_identifier extends SimpleNode {
  public ASTrhs_identifier(int id) {
    super(id);
  }

  public ASTrhs_identifier(HOPE6 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HOPE6Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=9b046d6cfae49ea5c0f65a3153bc836a (do not edit this line) */
