/* Generated By:JJTree: Do not edit this line. ASTvalue_declaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTvalue_declaration extends SimpleNode {
  public ASTvalue_declaration(int id) {
    super(id);
  }

  public ASTvalue_declaration(HOPE6 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HOPE6Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=cc5b61c755730710fdc183cb5095ad18 (do not edit this line) */
