/* Generated By:JavaCC: Do not edit this line. HOPE6TreeConstants.java Version 5.0 */
public interface HOPE6TreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTMAIN = 1;
  public int JJTFUNCTION_DECLARATIONS = 2;
  public int JJTFUNCTION = 3;
  public int JJTSTATEMENT_BLOCK = 4;
  public int JJTSTATEMENT = 5;
  public int JJTEXPRESSION = 6;
  public int JJTCONDITION = 7;
  public int JJTFRAGMENT = 8;
  public int JJTFUNCTION_CALL = 9;
  public int JJTINTEGER = 10;
  public int JJTSTRING = 11;
  public int JJTBOOL = 12;
  public int JJTASSIGNMENT = 13;
  public int JJTDECLARATION = 14;
  public int JJTPRINT = 15;
  public int JJTIF_STATEMENT = 16;
  public int JJTWHILE_LOOP = 17;
  public int JJTLHS_IDENTIFIER = 18;
  public int JJTRHS_IDENTIFIER = 19;
  public int JJTTYPE = 20;
  public int JJTPARAMETER_LIST = 21;
  public int JJTPARAMETER = 22;
  public int JJTARGUMENT_LIST = 23;
  public int JJTARGUMENT = 24;
  public int JJTBINARY_ARITH_OP = 25;
  public int JJTARITH_OP = 26;
  public int JJTBINARY_LOGIC_OP = 27;
  public int JJTLOGIC_OP = 28;
  public int JJTCOMP_OP = 29;


  public String[] jjtNodeName = {
    "program",
    "main",
    "function_declarations",
    "function",
    "statement_block",
    "statement",
    "expression",
    "condition",
    "fragment",
    "function_call",
    "integer",
    "string",
    "bool",
    "assignment",
    "declaration",
    "print",
    "if_statement",
    "while_loop",
    "lhs_identifier",
    "rhs_identifier",
    "type",
    "parameter_list",
    "parameter",
    "argument_list",
    "argument",
    "binary_arith_op",
    "arith_op",
    "binary_logic_op",
    "logic_op",
    "comp_op",
  };
}
/* JavaCC - OriginalChecksum=bca5b8eade0ba5d30a57365efec1e10c (do not edit this line) */
