/* Generated By:JavaCC: Do not edit this line. HOPE6TreeConstants.java Version 5.0 */
public interface HOPE6TreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTSTATEMENT_BLOCK = 1;
  public int JJTSTATEMENT = 2;
  public int JJTVOID = 3;
  public int JJTEXPRESSION = 4;
  public int JJTCONDITION = 5;
  public int JJTINTEGER = 6;
  public int JJTSTRING = 7;
  public int JJTBOOL = 8;
  public int JJTARRAY = 9;
  public int JJTASSIGNMENT = 10;
  public int JJTVALUE_DECLARATION = 11;
  public int JJTARRAY_DECLARATION = 12;
  public int JJTARRAY_SIZE = 13;
  public int JJTPRINT = 14;
  public int JJTIF_STATEMENT = 15;
  public int JJTWHILE_LOOP = 16;
  public int JJTLHS_IDENTIFIER = 17;
  public int JJTRHS_IDENTIFIER = 18;
  public int JJTTYPE = 19;
  public int JJTARRAY_TYPE = 20;
  public int JJTBINARY_ARITH_OP = 21;
  public int JJTBINARY_LOGIC_OP = 22;
  public int JJTCOMP_OP = 23;


  public String[] jjtNodeName = {
    "program",
    "statement_block",
    "statement",
    "void",
    "expression",
    "condition",
    "integer",
    "string",
    "bool",
    "array",
    "assignment",
    "value_declaration",
    "array_declaration",
    "array_size",
    "print",
    "if_statement",
    "while_loop",
    "lhs_identifier",
    "rhs_identifier",
    "type",
    "array_type",
    "binary_arith_op",
    "binary_logic_op",
    "comp_op",
  };
}
/* JavaCC - OriginalChecksum=029c1c6d348a25c79be9f9aff2e75aa0 (do not edit this line) */
