/* Generated By:JavaCC: Do not edit this line. HOPE6TreeConstants.java Version 5.0 */
public interface HOPE6TreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTSTATEMENT_BLOCK = 1;
  public int JJTSTATEMENT = 2;
  public int JJTVOID = 3;
  public int JJTEXPRESSION = 4;
  public int JJTCONDITION = 5;
  public int JJTINTEGER = 6;
  public int JJTSTRING = 7;
  public int JJTBOOL = 8;
  public int JJTASSIGNMENT = 9;
  public int JJTDECLARATION = 10;
  public int JJTPRINT = 11;
  public int JJTIF_STATEMENT = 12;
  public int JJTWHILE_LOOP = 13;
  public int JJTARRAY = 14;
  public int JJTIDENTIFIER = 15;
  public int JJTTYPE = 16;
  public int JJTBINARY_ARITH_OP = 17;
  public int JJTBINARY_LOGIC_OP = 18;
  public int JJTCOMP_OP = 19;


  public String[] jjtNodeName = {
    "program",
    "statement_block",
    "statement",
    "void",
    "expression",
    "condition",
    "integer",
    "string",
    "bool",
    "assignment",
    "declaration",
    "print",
    "if_statement",
    "while_loop",
    "array",
    "identifier",
    "type",
    "binary_arith_op",
    "binary_logic_op",
    "comp_op",
  };
}
/* JavaCC - OriginalChecksum=5d5b03974c5985a1211ab470cd05f3c0 (do not edit this line) */
