/* Generated By:JavaCC: Do not edit this line. HOPE1Visitor.java Version 5.0 */
public interface HOPE1Visitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTprogram node, Object data);
  public Object visit(ASTstatement_block node, Object data);
  public Object visit(ASTstatement node, Object data);
  public Object visit(ASTexpression node, Object data);
  public Object visit(ASTfragment node, Object data);
  public Object visit(ASTbinary_arith_op node, Object data);
}
/* JavaCC - OriginalChecksum=6ace362057f28f1219bb727895ac5668 (do not edit this line) */
