/* Generated By:JJTree&JavaCC: Do not edit this line. HOPE1Constants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface HOPE1Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PRINT = 13;
  /** RegularExpression Id. */
  int LBR = 14;
  /** RegularExpression Id. */
  int RBR = 15;
  /** RegularExpression Id. */
  int SEMIC = 16;
  /** RegularExpression Id. */
  int PLUS_SIGN = 17;
  /** RegularExpression Id. */
  int MINUS_SIGN = 18;
  /** RegularExpression Id. */
  int MUL_SIGN = 19;
  /** RegularExpression Id. */
  int DIV_SIGN = 20;
  /** RegularExpression Id. */
  int NUM = 21;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 22;
  /** RegularExpression Id. */
  int OTHER = 23;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_COMMENT = 1;
  /** Lexical state. */
  int IN_SINGLE_LINE_COMMENT = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"/*\"",
    "\"//\"",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 10>",
    "<token of kind 11>",
    "<token of kind 12>",
    "\"print\"",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "<NUM>",
    "<INTEGER_LITERAL>",
    "<OTHER>",
  };

}
