/* Generated By:JavaCC: Do not edit this line. HOPE1Visitor.java Version 5.0 */
public interface HOPE1Visitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTprogram node, Object data);
  public Object visit(ASTstatement_block node, Object data);
  public Object visit(ASTstatement node, Object data);
  public Object visit(ASTexpression node, Object data);
  public Object visit(ASTfragment node, Object data);
  public Object visit(ASTbinary_arith_op node, Object data);
}
/* JavaCC - OriginalChecksum=58e3ff1f84cad499f1ce7848df5cde4b (do not edit this line) */
