/* Generated By:JavaCC: Do not edit this line. HOPE1Visitor.java Version 5.0 */
public interface HOPE1Visitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTprogram node, Object data);
  public Object visit(ASTstatement_block node, Object data);
  public Object visit(ASTstatement node, Object data);
  public Object visit(ASTexpression node, Object data);
  public Object visit(ASTinteger node, Object data);
  public Object visit(ASTbinary_arith_op node, Object data);
}
/* JavaCC - OriginalChecksum=24e01a6e0b8568ba59fe377da8796c37 (do not edit this line) */
