/* Generated By:JavaCC: Do not edit this line. HOPE1TreeConstants.java Version 5.0 */
public interface HOPE1TreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTSTATEMENT_BLOCK = 1;
  public int JJTSTATEMENT = 2;
  public int JJTVOID = 3;
  public int JJTEXPRESSION = 4;
  public int JJTINTEGER = 5;
  public int JJTBINARY_ARITH_OP = 6;


  public String[] jjtNodeName = {
    "program",
    "statement_block",
    "statement",
    "void",
    "expression",
    "integer",
    "binary_arith_op",
  };
}
/* JavaCC - OriginalChecksum=aefa2f96c9c4ad11d88ba8e9114be0f0 (do not edit this line) */
