/* Generated By:JJTree: Do not edit this line. ASTfragment.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTfragment extends SimpleNode {
  public ASTfragment(int id) {
    super(id);
  }

  public ASTfragment(HOPE5 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HOPE5Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=3b7b8e9a190b4659c7314f2e17dc3de5 (do not edit this line) */
