/* Generated By:JJTree: Do not edit this line. ASTwhile_loop.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTwhile_loop extends SimpleNode {
  public ASTwhile_loop(int id) {
    super(id);
  }

  public ASTwhile_loop(HOPE5 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HOPE5Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d2ec0aa466df7afe1da5e2be897cbd22 (do not edit this line) */
