/* Generated By:JavaCC: Do not edit this line. HOPE5TreeConstants.java Version 5.0 */
public interface HOPE5TreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTSTATEMENT_BLOCK = 1;
  public int JJTSTATEMENT = 2;
  public int JJTEXPRESSION = 3;
  public int JJTCONDITION = 4;
  public int JJTVOID = 5;
  public int JJTINTEGER = 6;
  public int JJTSTRING = 7;
  public int JJTBOOL = 8;
  public int JJTASSIGNMENT = 9;
  public int JJTDECLARATION = 10;
  public int JJTPRINT = 11;
  public int JJTIF_STATEMENT = 12;
  public int JJTWHILE_LOOP = 13;
  public int JJTLHS_IDENTIFIER = 14;
  public int JJTRHS_IDENTIFIER = 15;
  public int JJTTYPE = 16;
  public int JJTBINARY_ARITH_OP = 17;
  public int JJTBINARY_LOGIC_OP = 18;
  public int JJTCOMP_OP = 19;


  public String[] jjtNodeName = {
    "program",
    "statement_block",
    "statement",
    "expression",
    "condition",
    "void",
    "integer",
    "string",
    "bool",
    "assignment",
    "declaration",
    "print",
    "if_statement",
    "while_loop",
    "lhs_identifier",
    "rhs_identifier",
    "type",
    "binary_arith_op",
    "binary_logic_op",
    "comp_op",
  };
}
/* JavaCC - OriginalChecksum=bb6448aa0d1f7284b60f9be1d9a85546 (do not edit this line) */
