/* Generated By:JavaCC: Do not edit this line. HOPE4TreeConstants.java Version 5.0 */
public interface HOPE4TreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTSTATEMENT_BLOCK = 1;
  public int JJTSTATEMENT = 2;
  public int JJTEXPRESSION = 3;
  public int JJTCONDITION = 4;
  public int JJTFRAGMENT = 5;
  public int JJTINTEGER = 6;
  public int JJTSTRING = 7;
  public int JJTBOOL = 8;
  public int JJTASSIGNMENT = 9;
  public int JJTDECLARATION = 10;
  public int JJTPRINT = 11;
  public int JJTIF_STATEMENT = 12;
  public int JJTIDENTIFIER = 13;
  public int JJTTYPE = 14;
  public int JJTBINARY_ARITH_OP = 15;
  public int JJTBINARY_LOGIC_OP = 16;
  public int JJTCOMP_OP = 17;


  public String[] jjtNodeName = {
    "program",
    "statement_block",
    "statement",
    "expression",
    "condition",
    "fragment",
    "integer",
    "string",
    "bool",
    "assignment",
    "declaration",
    "print",
    "if_statement",
    "identifier",
    "type",
    "binary_arith_op",
    "binary_logic_op",
    "comp_op",
  };
}
/* JavaCC - OriginalChecksum=af08100f1a4de6c828240e9a227b802b (do not edit this line) */
