/* Generated By:JJTree&JavaCC: Do not edit this line. HOPE4Constants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface HOPE4Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PRINT = 13;
  /** RegularExpression Id. */
  int INT = 14;
  /** RegularExpression Id. */
  int STRING = 15;
  /** RegularExpression Id. */
  int BOOL = 16;
  /** RegularExpression Id. */
  int TRUE = 17;
  /** RegularExpression Id. */
  int FALSE = 18;
  /** RegularExpression Id. */
  int IF = 19;
  /** RegularExpression Id. */
  int ELSE = 20;
  /** RegularExpression Id. */
  int LBR = 21;
  /** RegularExpression Id. */
  int RBR = 22;
  /** RegularExpression Id. */
  int SEMIC = 23;
  /** RegularExpression Id. */
  int PLUS_SIGN = 24;
  /** RegularExpression Id. */
  int MINUS_SIGN = 25;
  /** RegularExpression Id. */
  int MUL_SIGN = 26;
  /** RegularExpression Id. */
  int DIV_SIGN = 27;
  /** RegularExpression Id. */
  int EQUALS = 28;
  /** RegularExpression Id. */
  int OR = 29;
  /** RegularExpression Id. */
  int AND = 30;
  /** RegularExpression Id. */
  int QUOTE = 31;
  /** RegularExpression Id. */
  int LCB = 32;
  /** RegularExpression Id. */
  int RCB = 33;
  /** RegularExpression Id. */
  int EQ = 34;
  /** RegularExpression Id. */
  int NEQ = 35;
  /** RegularExpression Id. */
  int GT = 36;
  /** RegularExpression Id. */
  int LT = 37;
  /** RegularExpression Id. */
  int GE = 38;
  /** RegularExpression Id. */
  int LE = 39;
  /** RegularExpression Id. */
  int NUM = 40;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 41;
  /** RegularExpression Id. */
  int ID = 42;
  /** RegularExpression Id. */
  int STRING_LITERAL = 43;
  /** RegularExpression Id. */
  int LETTER = 44;
  /** RegularExpression Id. */
  int OTHER = 45;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_COMMENT = 1;
  /** Lexical state. */
  int IN_SINGLE_LINE_COMMENT = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"/*\"",
    "\"//\"",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 10>",
    "<token of kind 11>",
    "<token of kind 12>",
    "\"print\"",
    "\"int\"",
    "\"string\"",
    "\"boolean\"",
    "\"true\"",
    "\"false\"",
    "\"if\"",
    "\"else\"",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"=\"",
    "\"|\"",
    "\"&\"",
    "\"\\\"\"",
    "\"{\"",
    "\"}\"",
    "\"==\"",
    "\"!=\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "<NUM>",
    "<INTEGER_LITERAL>",
    "<ID>",
    "<STRING_LITERAL>",
    "<LETTER>",
    "<OTHER>",
  };

}
